<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a class="btn" href="<?php echo $this->url(array('page' => $this->previous)); ?>">
                <i class="icon-backward"></i> Previous
            </a>
        <?php else: ?>
            <a class="btn disabled"><i class="icon-backward"></i> Previous</a> |
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a class="btn" href="<?php echo $this->url(array('page' => $page)); ?>">
                    <?php echo $page; ?>
                </a>
            <?php else: ?>
                <a class="btn disabled"><?php echo $page; ?></a>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a class="btn" href="<?php echo $this->url(array('page' => $this->next)); ?>">
                Next <i class="icon-forward"></i>
            </a>
        <?php else: ?>
            <a class="btn disabled">Next <i class="icon-forward"></i></a>
        <?php endif; ?>
    </div>
<?php endif; ?>