<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>data.vehiclefits.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/common.css" rel="stylesheet">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
</head>

<body>

    <?=$this->partial('navbar.phtml', array(
        'active'=>'browse'
    ))?>

    <div class="container-fluid">
        <?=$this->partial('alerts.phtml')?>
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <?=$this->layout()->sidebar?>
                </div><!--/.well -->
            </div><!--/span-->
            <div class="span9">
                <?=$this->layout()->content?>
            </div><!--/span-->
        </div><!--/row-->

        <hr>

        <?=$this->partial('footer.phtml')?>

    </div><!--/.fluid-container-->
</body>
</html>