<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>data.vehiclefits.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 100px;
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px;
        }
        .sidebar-nav h1 {
            font-size:15px;
            line-height:20px;
            margin:0;
        }

        .vehicles_list {
            width:100%;
        }

        .vehicles_list tr:nth-child(odd)		{ background-color:#eee; }
        .vehicles_list tr:nth-child(even)		{ background-color:#fff; }
        .vehicles_list tr:first-child                 {background-color:#fff;}
        .vehicles_list tr:hover{
            color:white;
            background-color:#6d3353;
            cursor:pointer;
        }
        .vehicles_list td, .vehicles_list th {
            padding:2px;
            padding-left:10px;
            padding-right:10px;
            text-align: left;
        }

        .paginationControl {
            text-align:right;
            float:right;
        }

        h1 {
            font-size:22.5px;
            line-height:20px;
            margin:0;
        }

        .container-fluid {
            margin: 0 auto;
            max-width: 1200px;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
</head>

<body>
    <?php
    $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');

    if ($flashMessenger->hasMessages())
    {
        ?>
        <div class="message success">
        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
            <?php echo $msg ?>
        <?php endforeach; ?>
        </div>
        <?php
    }
    ?>

    <?=$this->partial('navbar.phtml', array(
        'active'=>'browse'
    ))?>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <?=$this->layout()->sidebar?>
                </div><!--/.well -->
            </div><!--/span-->
            <div class="span9">
                <?=$this->layout()->content?>
            </div><!--/span-->
        </div><!--/row-->

        <hr>

        <?=$this->partial('footer.phtml')?>

    </div><!--/.fluid-container-->

</body>
</html>