<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>data.vehiclefits.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/common.css" rel="stylesheet">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
</head>

<body>
    <?=$this->partial('navbar.phtml',array(
        'active'=>Zend_Registry::get('active_page')
    ))?>

    <div class="container-fluid">
        <?=$this->partial('alerts.phtml')?>
        <?=$this->layout()->content?>
        <?=$this->partial('footer.phtml')?>
    </div><!--/.fluid-container-->

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/js/bootstrap.min.js"></script>
</body>
</html>