<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>data.vehiclefits.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/common.css" rel="stylesheet">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
</head>

<body>
    <?php
    $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');

    if ($flashMessenger->hasMessages())
    {
        ?>
        <div class="message success">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
        </div>
    <?php
    }
    ?>

    <?=$this->partial('navbar.phtml',array(
        'active'=>'download'
    ))?>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="row-fluid">
                <div class="span4">
                    <h2>CSV</h2>
                    <p>Download the data in CSV</p>
                    <p><a class="btn" href="<?=$this->url(array('controller'=>'download','action'=>'csv'),null,true)?>"><i class="icon-cloud-download icon-large"></i> Download</a></p>
                </div><!--/span-->
                <div class="span4">
                    <h2>YAML</h2>
                    <p>Under Construction</p>
                    <p><a class="btn disabled" href="#"><i class="icon-cloud-download icon-large"></i> Download</a></p>
                </div><!--/span-->
                <div class="span4">
                    <h2>XML</h2>
                    <p>Under Construction</p>
                    <p><a class="btn disabled" href="#"><i class="icon-cloud-download icon-large"></i> Download</a></p>
                </div><!--/span-->
            </div><!--/row-->

        </div><!--/row-->

        <?=$this->partial('footer.phtml')?>


    </div><!--/.fluid-container-->

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/js/bootstrap.min.js"></script>
</body>
</html>