<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>data.vehiclefits.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 100px;
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px;
        }
        .sidebar-nav h1 {
            font-size:15px;
            line-height:20px;
            margin:0;
        }


        h1 {
            font-size:22.5px;
            line-height:20px;
            margin:0;
        }

        .container-fluid {
            margin: 0 auto;
            max-width: 1200px;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }

        body {
            font-family: "museo-sans",helvetica,arial,sans-serif;
            letter-spacing: 0.1em;
        }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">


    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
</head>

<body>
<?php
$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');

if ($flashMessenger->hasMessages())
{
    ?>
    <div class="message success">
        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
            <?php echo $msg ?>
        <?php endforeach; ?>
    </div>
<?php
}
?>

<?=$this->partial('navbar.phtml',array(
    'active'=>'download'
))?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span4">
                <h2>CSV</h2>
                <p>Download the data in CSV</p>
                <p><a class="btn" href="<?=$this->url(array('controller'=>'download','action'=>'csv'),null,true)?>"><i class="icon-cloud-download icon-large"></i> Download</a></p>
            </div><!--/span-->
            <div class="span4">
                <h2>YAML</h2>
                <p>Under Construction</p>
                <p><a class="btn disabled" href="#"><i class="icon-cloud-download icon-large"></i> Download</a></p>
            </div><!--/span-->
            <div class="span4">
                <h2>XML</h2>
                <p>Under Construction</p>
                <p><a class="btn disabled" href="#"><i class="icon-cloud-download icon-large"></i> Download</a></p>
            </div><!--/span-->
        </div><!--/row-->

    </div><!--/row-->

    <?=$this->partial('footer.phtml')?>


</div><!--/.fluid-container-->

<script src="http://code.jquery.com/jquery.js"></script>
<script src="/js/bootstrap.min.js"></script>

</body>
</html>