<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>data.vehiclefits.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/common.css" rel="stylesheet">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
</head>

<body>
    <?php
    $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');

    if ($flashMessenger->hasMessages())
    {
        ?>
        <div class="message success">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
        </div>
    <?php
    }
    ?>

    <?=$this->partial('navbar.phtml',array(
        'active'=>'home'
    ))?>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="hero-unit">
                    <a href="https://github.com/vehiclefits/data.vehiclefits.com"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>

                    <h1>Open Source Automotive Data!</h1>
                    <p>Welcome to Vehicle Fits Data, open source automotive data. Free data for the community, created by the community</p>
                    <p><a href="<?=$this->url(array('controller'=>'browse'),null,true)?>" class="btn btn-primary">Browse Data <i class="icon-arrow-right"></i></a></p>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span4">
                    <h2>Data Share API</h2>
                    <p>User our two way APIs to automatically share data. As you add new vehicles to your website, you share them with us. As we add new vehicles, we share them with you.</p>
                    <p><a class="btn" href="#"><i class="icon-rss-sign"></i> Data Share API</a></p>
                </div><!--/span-->
                <div class="span4">
                    <h2>Download Data</h2>
                    <p>Download our data in a variety of formats: CSV, XML, YAML </p>
                    <p><a class="btn" href="<?=$this->url(array('controller'=>'download'),null,true)?>"><i class="icon-cloud-download"></i> Download</a></p>
                </div><!--/span-->
                <div class="span4">
                    <h2>Participate</h2>
                    <p>Help us moderate community suggestions by voting them up or down. Create suggestions of your own </p>
                    <p><a class="btn disabled" href="#"><i class="icon-lightbulb"></i> View details</a></p>
                </div><!--/span-->
            </div><!--/row-->

        </div><!--/row-->

        <?=$this->partial('footer.phtml')?>


    </div><!--/.fluid-container-->

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/js/bootstrap.min.js"></script>

</body>
</html>