<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>data.vehiclefits.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/common.css" rel="stylesheet">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
</head>

<body>

    <?=$this->partial('navbar.phtml',array(
        'active'=>'home'
    ))?>

    <div class="container-fluid">
        <?=$this->partial('alerts.phtml')?>
        <div class="row-fluid">
            <div class="span12">
                <div class="hero-unit">
                    <a href="https://github.com/vehiclefits/data.vehiclefits.com"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>

                    <h1>Open Source Automotive Data!</h1>
                    <p>Welcome to Vehicle Fits Data, open source automotive data. Free data for the community, created by the community</p>
                    <p><a href="<?=$this->url(array('controller'=>'browse'),null,true)?>" class="btn btn-primary">Browse Data <i class="icon-arrow-right"></i></a></p>
                </div>
            </div>

            <?=$this->layout()->content?>

        </div><!--/row-->

        <?=$this->partial('footer.phtml')?>


    </div><!--/.fluid-container-->

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/js/bootstrap.min.js"></script>

</body>
</html>