<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="brand" href="/index.php"><img id="logo" src="/images/logo.png" /></a>
            <div class="nav-collapse collapse">

                <p class="navbar-text pull-right">

                    <?php
                    $user = bootstrap::getInstance()->getUser();
                    if($user) {
                        ?>
                        Logged in as <?=$this->escape($user['email'])?>.<br />
                        <a href="<?=$this->url(array('controller'=>'user','action'=>'dashboard'),null,true)?>">Dashboard</a> |
                        <a href="<?=$this->url(array('controller'=>'user','action'=>'logout'),null,true)?>">Log Out</a>
                        <?php
                    } else {
                        ?>
                        <a href="<?=$this->url(array('controller'=>'user','action'=>'login'),null,true)?>">Log In</a> |
                        <a href="<?=$this->url(array('controller'=>'user','action'=>'register'),null,true)?>">Register</a>
                        <?php
                    }
                    ?>
                </p>

                <ul class="nav nav-pills">
                    <li <?=$this->active=='home'?'class="active"':''?>><a href="/"><i class="icon-home"></i> Home</a></li>
                    <li <?=$this->active=='browse'?'class="active"':''?>>
                        <a href="<?=$this->url(array('controller'=>'browse'),null,true)?>"><i class="icon-search"></i> Browse</a>
                    </li>
                    <li <?=$this->active=='download'?'class="active"':''?>>
                        <a href="<?=$this->url(array('controller'=>'download'),null,true)?>"><i class="icon-cloud-download"></i> Download</a>
                    </li>
                    <li <?=$this->active=='api'?'class="active"':''?>>
                        <a href="<?=$this->url(array('controller'=>'api'),null,true)?>"><i class="icon-rss-sign"></i> API</a>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>