<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/index.php"><img id="logo" src="/images/logo.png" /></a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    Logged in as <a href="#" class="navbar-link">Username</a>
                </p>
                <ul class="nav">
                    <li <?=$this->active=='home'?'class="active"':''?>><a href="/">Home</a></li>
                    <li <?=$this->active=='browse'?'class="active"':''?>><a href="<?=$this->url(array('controller'=>'browse'),null,true)?>">Browse</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>