<h1>User dashboard</h1>

<h2>Uploaded Files</h2>
<?php
if(!count($this->uploaded_files)) {
    echo 'You have no uploads.';
} else {
    ?>
    <table class="uploaded_files">
        <tr>
            <th>File</th>
            <th>Uploaded</th>
            <th>File Size</th>
            <th>Status</th>
        </tr>
        <?php
        foreach($this->uploaded_files as $uploaded_file) {
            ?>
            <tr>
                <td><?=$this->escape($uploaded_file['name'])?></td>
                <td><?=$this->escape($uploaded_file['uploaded'])?></td>
                <td><?=$this->escape($uploaded_file['size'])?></td>
                <td>{status}</td>
            </tr>
        <?php
        }
        ?>
    </table>
    <?php
}
