<?php
$search = new VF_Search;
$search->setRequest($this->request);
$search->getFlexible()->storeFitInSession();

?>

<form action="<?=$this->url(array('controller'=>'browse'),null,true)?>" method="<?= $search->getMethod() ?>" id="<?= $search->formId() ?>" name="<?= $search->formId() ?>">
    <input type="hidden" id="vafProduct" value="<?= $search->getProductId() ?>"/>

    <!-- start "category chooser" -->
    <?php
    echo '<input type="hidden" name="category" id="categorySelect" value="?" />';
    ?>
    <!-- end "category chooser" -->

    <?php
    $levels = $search->getLevels();

    $searchLevel = new VF_SearchLevel();

    $displayLevels = $search->getLevels();
    $c = count($displayLevels);

    for ($i = 0; $i < $c; $i++) {
        $level = $displayLevels[$i];
        $prevLevel = ($i > 0) ? $displayLevels[$i - 1] : false;
        echo $searchLevel->display($search, $level, $prevLevel, $this->br_tags);
    }

    if ($search->showSearchButton()) {

        ?>
        <a href="#" id="vafClear" class="btn"><i class="icon-undo"></i> <?= $search->getClearText() ?></a>
        <a href="#" class="btn btn-primary vafSubmit"><i class="icon-search"></i> <?= $search->getSubmitText() ?></a>
        <?php
    }
    ?>
</form>

<!-- start VAF -->
<script src="/jquery-1.7.1.min.js" type="text/javascript" language="javascript"></script>
<script src="/jquery.metadata.pack.js" type="text/javascript" language="javascript"></script>
<script src="/index.php/js?front=1" type="text/javascript" language="javascript"></script>
<!-- end VAF -->